spring:
  application:
     name: account-service
  freemarker:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

server:
  port: 2222
