eureka:
  image: "eureka:1.0.0-SNAPSHOT"
  hostname: eureka
  name: eureka
  ports:
   - "8761:8761"

config:
  image: "config:1.0.0-SNAPSHOT"
  hostname: config
  name: config
  links:
    - eureka
  environment:
     EUREKA_HOST: eureka
     EUREKA_PORT: 8761
  ports:
    - "8888:8888"

account-server:
  image: "account-service:1.0.0-SNAPSHOT"
  hostname: account-service
  name: account-service
  links:
    - eureka
    - config
  ports:
   - "2222:2222"
  environment:
      EUREKA_HOST: eureka
      EUREKA_PORT: 8761